### ISSUE TITLE
Demo app does not get raw value

### ISSUE THREAD

**Issue by onuh** [andreszs/cordova-plugin-google-code-scanner#1]
The demo app strips off any XML tags in QR code content. It only returns value in between an XML embedded into QR code

**Comment by onuh** [comment]
I get error: "Must not be called on the main application thread" when i tried to use the plugin

**Comment by onuh** [comment]
Issue was resolved with the following code. Basically, google scanner builder must be launched from a background thread.

Runnable r = new Runnable() {
                public void run() {
                    GmsBarcodeScannerOptions options = new GmsBarcodeScannerOptions.Builder()
                    .setBarcodeFormats(barcodeFormats)
                    .build();

            // Configure options
            Context context = cordova.getContext();
            GmsBarcodeScanner scanner = GmsBarcodeScanning.getClient(context, options);

            try {
                scanner
                        .startScan()
                        .addOnSuccessListener(
                                barcode -> {
                                    // Task completed successfully
                                    Log.w(TAG, "Code scanned");
                                    JSONObject jsonBarcode = getJsonFromBarcode(barcode);
                                    mCallbackContext.success(jsonBarcode);
                                })
                        .addOnFailureListener(
                                e -> {
                                    // Task failed with an exception
                                    Log.e(TAG, e.getMessage());
                                    mCallbackContext.error(e.getMessage());
                                })
                        .addOnCanceledListener(() -> {
                            // Task canceled
                            Log.w(TAG, "Canceled by user");
                            mCallbackContext.error("Canceled");
                        });
            } catch (Exception e) {
                mCallbackContext.error(e.getMessage());
            }
                }
            };
       
            new Thread(r).start();

**Comment by andreszs** [comment]
Thanks @onuh, can you create a PR to fix this? Otherwise I'll try to make it next week.

**Comment by onuh** [comment]
Hello @andreszs I created a PR here: https://github.com/andreszs/cordova-plugin-google-code-scanner/pull/3/commits/9b50c560c142b7b4fc85493242493cfe36cdd493

**Comment by andreszs** [comment]
Thanks, merged #3 and published as 1.1.0.
